services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3307:3306"
    networks:
      - catnet
    restart: unless-stopped

  redis:
    image: redis:7.2.7-alpine3.21
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - catnet

  catapi:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - catnet
    env_file:
      - nginx.env
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - catnet
    volumes:
      - ./app:/var/www/html
    env_file:
      - nginx.env
    expose:
      - 9000
    restart: unless-stopped
    depends_on:
      - redis
      - db

networks:
  catnet:
    driver: bridge
