services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3307:3306"
    networks:
      - catnet

  catapi:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - catnet
    env_file:
      - nginx.env
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - catnet
    volumes:
      - ./app:/var/www/html
      - ./vendor:/var/www/vendor
    env_file:
      - nginx.env
    expose:
      - 9000

networks:
  catnet:
    driver: bridge
