services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "catrootdb"
      MARIADB_DATABASE: "catdb.mysql"
      MARIADB_USER: "catdb"
      MARIADB_PASSWORD: "catdb"
    ports:
      - "3307:3306"

  catapi:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - catnet
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - catnet
    volumes:
      - ./app:/var/www/html
    expose:
      - 9000

networks:
  catnet:
    driver: bridge
