<?php
/*
 * Copyright (c) 2025.
 *
 * Code is licensed under GNU GPLv3 License and available in the Copying file.
 * Code was written by:
 * - Simone Robaldo ( simone.robaldo at itiscuneo.eu )
 * - Giulia Vadelli ( giulia.vadelli at itiscuneo.eu )
 * - Daniele Torchio ( daniele.torchio at itiscuneo.eu )
 */

require "vendor/autoload.php";

use BaseHandlers\Cats;
use BaseHandlers\Users;
use Enums\NotFoundReason;
use Exceptions\BadRequestException;
use Exceptions\BaseApiException;
use Exceptions\MethodNotAllowedException;
use Exceptions\NotFoundException;
use Exceptions\ServerException;
use Exceptions\UnauthorizedException;
use Exceptions\UserAlreadyExistsException;
use Exceptions\UserNotVerifiedException;
use Utilities\CommonJsons;

ini_set('display_errors', 0);
ini_set('log_errors', 1);

set_error_handler(function ($severity, $message, $file, $line) {
    http_response_code(500); // Set the HTTP status code
    $json = [
       'error' => "Server Error",
       'status' => 500,
    ];

    if (getenv("DEBUG_MODE") == "true") {
        $json["file"] = $file;
        $json["line"] = $line;
        $json["severity"] = $severity;
        $json["exception"] = $message;
    }

    echo json_encode($json);


    exit; // Stop script execution after handling the error
});

register_shutdown_function(function () {
    $error = error_get_last();
    if ($error !== null) {
        http_response_code(500);
        $json = [
            'error' => "Server Error",
            'status' => 500
        ];

        if(getenv("DEBUG_MODE") == "true") {
            $json["file"] = $error["file"];
            $json["line"] = $error["line"];
            $json["exception"] = $error["message"];
            $json["type"] = $error["type"];
        }

        echo json_encode($json);
    }
});


/**
 * The base URL of the API to which requests will be made.
 *
 * This variable typically holds the root endpoint of the API
 * and is used as the starting point for constructing full API request URLs.
 * It serves as the foundation for concatenating specific routes
 * or endpoints when making HTTP requests.
 */
$apiBase = "/api/v1/";
/**
 * @var string $uri
 *
 * Represents a Uniform Resource Identifier (URI). It is used to identify a resource
 * on a network typically through a web address or other standardized addressing format.
 * The string should follow the general URI format as specified by the relevant standards
 * or conventions.
 */
$uri = str_replace($apiBase, "", $_SERVER['REQUEST_URI']);

/**
 * An array containing the components of a URI.
 *
 * This variable is intended to store the parsed segments of a URI,
 * typically resulting from breaking a URI into its constituent parts
 * such as scheme, host, path, query, and fragment.
 *
 * It can be used to access or manipulate individual components
 * of the URI for further processing or logic implementation.
 *
 * The structure and keys of the array depend on the specific parsing logic used.
 */
$uriParts = explode("/", $uri);
header("Content-type: application/json");


/**
 * Handles an incoming HTTP request and routes it based on the first segment of the URI.
 *
 * @param array $uriParts An array representing the parts of the URI, where the first element determines the route.
 * @return string The response generated by the handler corresponding to the specified path.
 * @throws NotFoundException If the path does not match any known routes or if `Users::handler()` throws it.
 * @throws BadRequestException If `Users::handler()` throws it due to a badly formatted request.
 * @throws UserNotVerifiedException If `Users::handler()` throws it because the user's account was not verified.
 * @throws UnauthorizedException If `Users::handler()` throws it due to authorization issues.
 * @throws UserAlreadyExistsException If `Users::handler()` throws it because of an existing email address.
 * @throws MethodNotAllowedException If `Users::handler()` throws it because the method is not allowed.
 * @throws ServerException If `Users::handler()` throws it due to a fatal server error.
 */
function handleRequest(array $uriParts): string {
    return match($uriParts[0]) {
        "cats" => Cats::handler($uriParts),
        "users" => Users::handler($uriParts),
        "info" => CommonJsons::$Info,
        default => throw new NotFoundException(NotFoundReason::PATH_NOT_FOUND)
    };
}

try {
    echo match ($uriParts[0]) {
        "users" => Users::handler($uriParts),
        "cats" => Cats::handler($uriParts),
        "info" => CommonJsons::$Info,
        default => throw new NotFoundException(NotFoundReason::PATH_NOT_FOUND),
    };
} catch (BaseApiException $ex) {
    http_response_code($ex::$HTTP_STATUS_CODE);
    error_log($ex->toLog());
    echo $ex->toJson();
}

